# Add 'test' label to any change to *.spec.js files within the source dir
test:
  - src/**/*.spec.ts

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
source:
  - any: ['src/**/*', '!src/docs/*']

# Add 'frontend` label to any change to *.js files as long as the `main.js` hasn't changed
frontend:
  - any: ['src/**/*.js']
    all: ['!src/main.js']

test-centre-journal:
  - any: ['src/store/test-centre-journal/**/*', 'src/app/pages/test-centre-journal/**/*']

home:
  - any: ['src/app/home', 'src/theme']
