name: Branch name

on: push

jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
        id: extract_branch

      #      - uses: actions/checkout@v3
      #        with:
      #          ref: ${{ steps.extract_branch-name.outputs.branch }}

      - name: Branch name
        run: |
          echo running on branch ${GITHUB_REF##*/}
          echo ${{ toJson(steps.extract_branch-name) }}
