name: Pull Request Labeler

on: pull_request

jobs:
  triage:
    with:
      configuration-path: .github/labeler.yaml
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
