name: Lint

on: [push]

jobs:
  install-node:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - run: npm install

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: npm run lint
        run: |
          npm run lint