name: Bump version

on:
  issue_comment
  #    branches:
  #      - 'release-**'

env:
  CI_COMMIT_EMAIL: username@users.noreply.github.com
  CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
  CI_COMMIT_AUTHOR: Continuous Integration

jobs:
  bump-minor:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'bump@minor') }}
    steps:
      - name: Read branch name
        env:
          BRANCH: ${{ github.ref_name }}
        id: branch-name
        run: echo "::set-output name=fragment::${BRANCH##*/"

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch-name.outputs.fragment }}

      - name: Read .nvmrc
        id: nvm
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Install dependencies
        run: npm ci

      - name: Git credentials setup
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"

      - name: Bump minor version
        run: |
          npm version minor
          npm run sync-versions

      - name: GIT commit & push all changed files
        run: |
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push

  bump-patch:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'bump@patch') }}
    steps:
      - name: Read branch name
        env:
          BRANCH: ${{ github.ref_name }}
        id: branch-name
        run: echo "::set-output name=fragment::${BRANCH##*/"

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch-name.outputs.fragment }}

      - name: Read .nvmrc
        id: nvm
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Install dependencies
        run: npm ci

      - name: Git credentials setup
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"

      - name: Bump patch version
        run: |
          npm version patch
          npm run sync-versions

      - name: GIT commit & push all changed files
        run: |
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push

