name: Deploy

on: issue_comment

jobs:
  runs-on: ubuntu-latest

  bump-major:
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Bump major version
        run: |
          echo ${{ github.event.comment.body }}

  bump-minor:
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Bump minor version
        run: |
          echo ${{ github.event.comment.body }}

  bump-patch:
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Bump patch version
        run: |
          echo ${{ github.event.comment.body }}

