name: Deploy

on: issue_comment

jobs:
  pr_commented:
    runs-on: ubuntu-latest

    steps:
      - name: Echo github event

        if: ${{ github.event.issue.pull_request }}

        run: |
          echo hello
          echo ${{ toJson(github) }}
          echo ${{ github.event.comment.body }}

