name: Deploy

on:
  issue_comment:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get PR SHA
        id: sha
        uses: actions/github-script@v4
        with:
        result-encoding: string
        runs: |
          echo hello
          echo ${{ github.event.issue.pull_request }}
          echo ${{ github.event.comment.body }}

        if: ${{ github.event.issue.pull_request && github.event.comment.body == '/deploy'}}

        script: |
          const { owner, repo, number } = context.issue;
          const pr = await github.pulls.get({
            owner,
            repo,
            pull_number: number,
          });
          return pr.data.head.sha

      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.sha.outputs.result }}

      - name: Run deployment
        run: make deploy
