name: Bump version

on:
  issue_comment
#    branches:
#      - 'release-**'

jobs:
  bump-minor:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'bump@minor') }}
    steps:
      - uses: actions/checkout@v3

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}  

      - name: Install dependencies
        run: npm ci

      - name: Git credentials setup
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Bump minor version
        run: |
          npm version minor
          npm run sync-versions

  bump-patch:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'bump@patch') }}
    steps:
      - uses: actions/checkout@v3

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Install dependencies
        run: npm ci

      - name: Git credentials setup
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Bump patch version
        run: |
          npm version patch
          npm run sync-versions
